# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node (for interop testing)
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build smoke test
      run: go build ./cmd/...

    - name: install node ssb-stack
      run: |
        pushd muxrpc/test/nodejs
        npm ci
        popd

    - name: All the Test
      run: go test ./...

    - name: update style.css
      run: |
        pushd web/styles
        npm ci
        npm run compile-prod
        popd

    - name: push updated style.css
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update production style.css
        file_pattern: web/assets/style.css
